data:
- bg_channel: 1
  cell_def: ''
  cube_dir: Z:\Blackmore_Lab\Brainglobe\Trained_Models\New ones\20241231\cells
  signal_channel: 0
  type: cell
- bg_channel: 1
  cell_def: ''
  cube_dir: Z:\Blackmore_Lab\Brainglobe\Trained_Models\New ones\20241231\non_cells
  signal_channel: 0
  type: no_cell
