data:
- bg_channel: 1
  cell_def: ''
  cube_dir: \\134.48.78.185\blac\2_Connectome\3_Nuclei_Detection\1_Brains\349_CNT_01_02\349_CNT_01_02_1p625x_z4\training_data\cells
  signal_channel: 0
  type: cell
- bg_channel: 1
  cell_def: ''
  cube_dir: \\134.48.78.185\blac\2_Connectome\3_Nuclei_Detection\1_Brains\349_CNT_01_02\349_CNT_01_02_1p625x_z4\training_data\non_cells
  signal_channel: 0
  type: no_cell
