data:
- bg_channel: 1
  cell_def: ''
  cube_dir: Z:\Blackmore_Lab\Brainglobe\336\336_BL\336_Static_1.61x_BL_napari_output\20241114\cells
  signal_channel: 0
  type: cell
- bg_channel: 1
  cell_def: ''
  cube_dir: Z:\Blackmore_Lab\Brainglobe\336\336_BL\336_Static_1.61x_BL_napari_output\20241114\non_cells
  signal_channel: 0
  type: no_cell
